In [3]:
import torch

# 创建张量
tensor1 = torch.tensor([1, 2, 3])  # 从列表创建张量
tensor2 = torch.zeros((2, 3))  # 创建全零张量
tensor3 = torch.ones((2, 3))  # 创建全一张量
tensor4 = torch.rand((2, 3))  # 创建随机张量

# 张量的基本属性
print(tensor1.shape)  # 查看张量的形状
print(tensor1.dtype)  # 查看张量的数据类型
print(tensor1.device)  # 查看张量所在的设备（CPU/GPU）

# 张量的基本操作
tensor5 = tensor1 + 1  # 张量加法
tensor6 = tensor1 * 2  # 张量乘法
tensor7 = tensor1 @ tensor1.T  # 矩阵乘法（点积）
tensor8 = tensor1.sum()  # 求和
# tensor9 = tensor1.mean()  # 求均值

# 改变张量形状
tensor10 = tensor2.view(3, 2)  # 改变形状
tensor11 = tensor2.reshape(3, 2)  # 改变形状（类似view）

# 张量与NumPy的互操作
import numpy as np

array = np.array([1, 2, 3])
tensor12 = torch.from_numpy(array)  # NumPy数组转张量
array2 = tensor12.numpy()  # 张量转NumPy数组

# 张量在GPU上的操作
if torch.cuda.is_available():
    tensor13 = tensor1.to("cuda")  # 将张量移动到GPU
    print(tensor13.device)

torch.Size([3])
torch.int64
cpu
cuda:0


In [4]:
import torch

# 创建张量
x = torch.tensor([[3, 2], [3, 1]])
x = torch.zeros((2, 3))  # 创建全零张量
x = torch.zeros(3)
x = torch.zeros_like(torch.tensor([[1, 2], [3, 4]]))  # 创建与给定张量相同形状的全零张量
x = torch.ones((2, 3))  # 创建全一张量
x = torch.rand((2, 3))  # 创建随机张量
x = torch.randn((2, 3))  # 创建标准正态分布随机张量
x = torch.randint(0, 10, (2, 3))  # 创建随机整数张量
x

tensor([[6, 4, 4],
        [4, 0, 3]])

In [5]:
x.shape
x.dtype
x.device  # 查看张量所在的设备（CPU/GPU）

device(type='cpu')

In [6]:
x1 = torch.tensor([1.0, 2.0, 3.0])  # 从列表创建张量
x2 = torch.tensor([[4, 5, 6]])  # 从嵌套列表创建张量
x = x1 + 1  # 张量加法
x = x1 * 2  # 张量乘法
x = x2 @ x2.T  # 矩阵乘法（点积）
x = x1.sum()  # 求和
x = x1.mean()  # 求均值
x

tensor(2.)

In [7]:
x = x1.view(3, 1)  # 改变形状
x = x1.reshape(3, 1)  # 改变形状（类似view）
x

tensor([[1.],
        [2.],
        [3.]])

In [8]:
import numpy as np

x = torch.from_numpy(np.array([[1, 2], [3, 4]]))  # NumPy数组转张量
x = x.numpy()  # 张量转NumPy数组
x

array([[1, 2],
       [3, 4]])

In [12]:
a = torch.ones((2, 3))
b = torch.ones((2, 3))

print(a + b)
print(a.add(b))
print(a.add_(b))
print(a)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [13]:
print(a - b)
print(a.sub(b))
print(a.sub_(b))
print(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [17]:
print(a * b)
print(a.mul(b))
print(a.mul_(b))
print(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [20]:
c = torch.ones((3, 2))
print(a @ c)

tensor([[3., 3.],
        [3., 3.]])


In [21]:
print(a / b)
print(a.div(b))
print(a.div_(b))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [23]:
d = torch.tensor([[1, 2], [2, 3]])
print(torch.pow(d, 2))

tensor([[1, 4],
        [4, 9]])


In [24]:
print(torch.exp(d))

tensor([[ 2.7183,  7.3891],
        [ 7.3891, 20.0855]])


In [25]:
print(torch.log(d))

tensor([[0.0000, 0.6931],
        [0.6931, 1.0986]])


In [26]:
print(torch.log10(d))

tensor([[0.0000, 0.3010],
        [0.3010, 0.4771]])


In [27]:
print(torch.sqrt(d))

tensor([[1.0000, 1.4142],
        [1.4142, 1.7321]])


In [31]:
a = torch.rand([2, 1, 3])
b = torch.rand(3)
c = a + b
print(a)
print(b)
print(c)

tensor([[[0.6598, 0.6371, 0.6933]],

        [[0.3437, 0.9041, 0.8012]]])
tensor([0.5157, 0.0389, 0.2242])
tensor([[[1.1755, 0.6760, 0.9176]],

        [[0.8593, 0.9430, 1.0254]]])


In [32]:
a = torch.rand(2, 2)
a = a * 10
print(a)

tensor([[4.4332, 2.9247],
        [8.8647, 0.4570]])


In [33]:
print(torch.floor(a))

tensor([[4., 2.],
        [8., 0.]])


In [34]:
print(torch.ceil(a))
print(torch.round(a))
print(torch.trunc(a))
print(torch.frac(a))
print(a % 2)

tensor([[5., 3.],
        [9., 1.]])
tensor([[4., 3.],
        [9., 0.]])
tensor([[4., 2.],
        [8., 0.]])
tensor([[0.4332, 0.9247],
        [0.8647, 0.4570]])
tensor([[0.4332, 0.9247],
        [0.8647, 0.4570]])
