In [2]:
import torch

In [2]:
a = torch.rand(2, 3)
print(a)

tensor([[0.0880, 0.3048, 0.0417],
        [0.7777, 0.0019, 0.2381]])


In [3]:
print(torch.cos(a))
print(torch.sin(a))

tensor([[0.9961, 0.9539, 0.9991],
        [0.7125, 1.0000, 0.9718]])
tensor([[0.0878, 0.3001, 0.0417],
        [0.7017, 0.0019, 0.2359]])


In [11]:
# torch.manual_seed(1)
a = torch.rand(2, 3)
print(torch.normal(mean=a, std=0.1))

tensor([[0.7260, 0.5903, 0.6681],
        [0.7026, 0.5858, 0.7830]])


In [13]:
a = torch.rand(1, 1)
print(a)
print(torch.norm(a, p=2))
print(torch.norm(a, p=1))

tensor([[0.1251]])
tensor(0.1251)
tensor(0.1251)


In [3]:
a = torch.rand(3, 4)
print(a)
print(torch.split(a, 1, dim=0))

tensor([[0.5170, 0.1692, 0.3657, 0.8787],
        [0.7310, 0.9538, 0.6612, 0.3692],
        [0.5962, 0.6783, 0.1048, 0.2695]])
(tensor([[0.5170, 0.1692, 0.3657, 0.8787]]), tensor([[0.7310, 0.9538, 0.6612, 0.3692]]), tensor([[0.5962, 0.6783, 0.1048, 0.2695]]))


In [16]:
a = torch.rand(3, 4)
b = torch.rand(3, 4)
print(a)
print(a.shape)
print(b)
print(b.shape)
out = torch.cat((a, b), dim=0)
print(out)
print(out.shape)

out = torch.cat((a, b), dim=1)
print(out)
print(out.shape)

tensor([[0.6536, 0.0049, 0.3962, 0.8145],
        [0.0456, 0.7569, 0.8782, 0.9941],
        [0.5236, 0.4033, 0.8367, 0.4388]])
torch.Size([3, 4])
tensor([[0.4370, 0.5965, 0.5085, 0.6097],
        [0.5881, 0.7496, 0.4230, 0.6656],
        [0.2333, 0.2882, 0.1538, 0.3566]])
torch.Size([3, 4])
tensor([[0.6536, 0.0049, 0.3962, 0.8145],
        [0.0456, 0.7569, 0.8782, 0.9941],
        [0.5236, 0.4033, 0.8367, 0.4388],
        [0.4370, 0.5965, 0.5085, 0.6097],
        [0.5881, 0.7496, 0.4230, 0.6656],
        [0.2333, 0.2882, 0.1538, 0.3566]])
torch.Size([6, 4])
tensor([[0.6536, 0.0049, 0.3962, 0.8145, 0.4370, 0.5965, 0.5085, 0.6097],
        [0.0456, 0.7569, 0.8782, 0.9941, 0.5881, 0.7496, 0.4230, 0.6656],
        [0.5236, 0.4033, 0.8367, 0.4388, 0.2333, 0.2882, 0.1538, 0.3566]])
torch.Size([3, 8])


In [17]:
out = torch.stack((a, b), dim=0)
print(out)
print(out.shape)

out = torch.stack((a, b), dim=1)
print(out)
print(out.shape)

tensor([[[0.6536, 0.0049, 0.3962, 0.8145],
         [0.0456, 0.7569, 0.8782, 0.9941],
         [0.5236, 0.4033, 0.8367, 0.4388]],

        [[0.4370, 0.5965, 0.5085, 0.6097],
         [0.5881, 0.7496, 0.4230, 0.6656],
         [0.2333, 0.2882, 0.1538, 0.3566]]])
torch.Size([2, 3, 4])
tensor([[[0.6536, 0.0049, 0.3962, 0.8145],
         [0.4370, 0.5965, 0.5085, 0.6097]],

        [[0.0456, 0.7569, 0.8782, 0.9941],
         [0.5881, 0.7496, 0.4230, 0.6656]],

        [[0.5236, 0.4033, 0.8367, 0.4388],
         [0.2333, 0.2882, 0.1538, 0.3566]]])
torch.Size([3, 2, 4])


In [19]:
a = torch.rand(3, 4)
print(a)
print(torch.reshape(a, (4, 3)))

tensor([[0.4324, 0.3921, 0.2262, 0.6090],
        [0.1457, 0.7581, 0.7015, 0.3900],
        [0.7020, 0.8606, 0.2783, 0.3878]])
tensor([[0.4324, 0.3921, 0.2262],
        [0.6090, 0.1457, 0.7581],
        [0.7015, 0.3900, 0.7020],
        [0.8606, 0.2783, 0.3878]])


In [20]:
print(torch.transpose(a, 0, 1))

tensor([[0.4324, 0.1457, 0.7020],
        [0.3921, 0.7581, 0.8606],
        [0.2262, 0.7015, 0.2783],
        [0.6090, 0.3900, 0.3878]])


In [29]:
b = torch.rand(3, 2, 4)
print(b)
print(b.shape)
out = torch.transpose(b, 2, 1)
print(out)
print(out.shape)

tensor([[[0.3471, 0.8671, 0.1282, 0.3842],
         [0.0700, 0.2105, 0.1860, 0.6618]],

        [[0.9020, 0.7855, 0.3964, 0.7002],
         [0.8992, 0.7170, 0.8706, 0.5219]],

        [[0.0210, 0.2473, 0.5925, 0.5017],
         [0.3634, 0.4535, 0.9112, 0.0305]]])
torch.Size([3, 2, 4])
tensor([[[0.3471, 0.0700],
         [0.8671, 0.2105],
         [0.1282, 0.1860],
         [0.3842, 0.6618]],

        [[0.9020, 0.8992],
         [0.7855, 0.7170],
         [0.3964, 0.8706],
         [0.7002, 0.5219]],

        [[0.0210, 0.3634],
         [0.2473, 0.4535],
         [0.5925, 0.9112],
         [0.5017, 0.0305]]])
torch.Size([3, 4, 2])


In [21]:
print(torch.t(a))

tensor([[0.4324, 0.1457, 0.7020],
        [0.3921, 0.7581, 0.8606],
        [0.2262, 0.7015, 0.2783],
        [0.6090, 0.3900, 0.3878]])


In [33]:
a = torch.rand(3, 1, 2)
print(a)
print(a.shape)
out = torch.squeeze(a)
print(out)
print(out.shape)

tensor([[[0.1297, 0.7620]],

        [[0.0424, 0.7052]],

        [[0.9155, 0.6276]]])
torch.Size([3, 1, 2])
tensor([[0.1297, 0.7620],
        [0.0424, 0.7052],
        [0.9155, 0.6276]])
torch.Size([3, 2])


In [43]:
print(a)
out = torch.unsqueeze(a, dim=-1)
print(out)
print(a.shape)

tensor([[[0.1297, 0.7620]],

        [[0.0424, 0.7052]],

        [[0.9155, 0.6276]]])
tensor([[[[0.1297],
          [0.7620]]],


        [[[0.0424],
          [0.7052]]],


        [[[0.9155],
          [0.6276]]]])
torch.Size([3, 1, 2])


In [37]:
print(a)
ut = torch.unbind(a, dim=1)
print(out)

tensor([[[0.1297, 0.7620]],

        [[0.0424, 0.7052]],

        [[0.9155, 0.6276]]])
(tensor([[0.1297, 0.7620]]), tensor([[0.0424, 0.7052]]), tensor([[0.9155, 0.6276]]))


In [48]:
c = torch.rand(3, 4)
out = torch.unsqueeze(c, dim=-1)
print(c)
print(c.shape)
print(out)
print(out.shape)

tensor([[0.2227, 0.2181, 0.7937, 0.8122],
        [0.2592, 0.6767, 0.7813, 0.4505],
        [0.8493, 0.6463, 0.3598, 0.4690]])
torch.Size([3, 4])
tensor([[[0.2227],
         [0.2181],
         [0.7937],
         [0.8122]],

        [[0.2592],
         [0.6767],
         [0.7813],
         [0.4505]],

        [[0.8493],
         [0.6463],
         [0.3598],
         [0.4690]]])
torch.Size([3, 4, 1])
