In [1]:
import torch

In [2]:
a = torch.rand(3, 4)

print(a.clamp(0.2, 0.8))  # Clamp values to be between 0.2 and 0.8

tensor([[0.2618, 0.7282, 0.2000, 0.2735],
        [0.7068, 0.2000, 0.8000, 0.8000],
        [0.2000, 0.2000, 0.6981, 0.4552]])


In [13]:
print(a)
print(
    torch.where(a > 0.5, a, torch.tensor(0.0))
)  # Replace values greater than 0.5 with 0
print(
    torch.index_select(a, dim=0, index=torch.tensor([0, 2]))
)  # Select rows 0 and 2 from tensor a
print(
    torch.gather(a, dim=0, index=torch.tensor([[0, 1], [2, 1]]))
)  # Gather values from a using the specified indices

print(
    torch.take(a, torch.tensor([0, 1, 2]))
)  # Take values from a using the specified indices

tensor([[0.2618, 0.7282, 0.0617, 0.2735],
        [0.7068, 0.0594, 0.9745, 0.8377],
        [0.0700, 0.1901, 0.6981, 0.4552]])
tensor([[0.0000, 0.7282, 0.0000, 0.0000],
        [0.7068, 0.0000, 0.9745, 0.8377],
        [0.0000, 0.0000, 0.6981, 0.0000]])
tensor([[0.2618, 0.7282, 0.0617, 0.2735],
        [0.0700, 0.1901, 0.6981, 0.4552]])
tensor([[0.2618, 0.0594],
        [0.0700, 0.0594]])
tensor([0.2618, 0.7282, 0.0617])
