In [67]:
import numpy as np
import torch
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [ ]:
# data
data = pd.read_csv("data/HousingData.csv", sep=",")
# print(data.head())
# print(data.shape)
data = data.fillna(data.mean())
x_train = data.iloc[:496, :-1].values
y_train = data.iloc[:496, -1].values
# print(x_train.shape)
# print(y_train.shape)
# print(y_train)
x_test = data.iloc[496:, :-1].values
y_test = data.iloc[496:, -1].values


# Net
class Net(torch.nn.Module):
    def __init__(self, input_size, output_size):
        super(Net, self).__init__()
        self.fc1 = torch.nn.Linear(input_size, output_size)

    def forward(self, x):
        x = self.fc1(x)
        return x


net = Net(input_size=13, output_size=1)

# loss
loss = torch.nn.MSELoss()

# optimizer
optimizer = torch.optim.SGD(net.parameters(), lr=0.0001)
# optimizer = torch.optim.Adam(net.parameters(), lr=0.0001)

# training
for epoch in range(1000):
    # convert numpy to tensor
    x_train_tensor = torch.tensor(x_train, dtype=torch.float32)
    y_train_tensor = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)

    # forward pass
    # y_pred = net(x_train_tensor)
    y_pred = net.forward(x_train_tensor)

    # compute loss
    l = loss(y_pred, y_train_tensor) * 0.01

    # print(y_train_tensor.shape)
    # print(y_pred.shape)

    # backward pass
    optimizer.zero_grad()
    l.backward()
    optimizer.step()

    print(f"Epoch {epoch + 1}, Loss: {l.item()}")
    print(y_pred[0:10])
    print(y_train_tensor[0:10])

Epoch 1, Loss: 156.05111694335938
tensor([[-109.3679],
        [-102.5068],
        [ -99.4273],
        [ -97.8950],
        [ -98.8634],
        [ -99.4936],
        [-105.9334],
        [-109.9636],
        [-107.4462],
        [-106.3054]], grad_fn=<SliceBackward0>)
tensor([[24.0000],
        [21.6000],
        [34.7000],
        [33.4000],
        [36.2000],
        [28.7000],
        [22.9000],
        [27.1000],
        [16.5000],
        [18.9000]])
Epoch 2, Loss: 31.19466781616211
tensor([[-43.0677],
        [-41.2711],
        [-38.8687],
        [-39.3837],
        [-39.9784],
        [-40.8114],
        [-38.2377],
        [-41.6449],
        [-39.9686],
        [-39.0887]], grad_fn=<SliceBackward0>)
tensor([[24.0000],
        [21.6000],
        [34.7000],
        [33.4000],
        [36.2000],
        [28.7000],
        [22.9000],
        [27.1000],
        [16.5000],
        [18.9000]])
Epoch 3, Loss: 13.142587661743164
tensor([[-17.6652],
        [-17.5699],
        [-15.

In [71]:
# data
data = pd.read_csv("data/HousingData.csv", sep=",")
# print(data.head())
# print(data.shape)
data = data.fillna(data.mean())
x_train = data.iloc[:496, :-1].values
y_train = data.iloc[:496, -1].values.reshape(-1, 1)
# print(x_train.shape)
# print(y_train.shape)
# print(y_train)
x_test = data.iloc[496:, :-1].values
y_test = data.iloc[496:, -1].values.reshape(-1, 1)

# standartd
scaler_y = StandardScaler()
y_train = scaler_y.fit_transform(y_train)
y_test = scaler_y.transform(y_test)
scaler_x = StandardScaler()
x_train = scaler_x.fit_transform(x_train)
x_test = scaler_x.transform(x_test)


# convert numpy to tensor
x_train_tensor = torch.tensor(x_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
# print(x_train_tensor.shape)
# print(y_train_tensor.shape)
x_test_tensor = torch.tensor(x_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)


# Net
class Net(torch.nn.Module):
    def __init__(self, input_size, output_size):
        super(Net, self).__init__()
        self.fc1 = torch.nn.Linear(input_size, output_size)

    def forward(self, x):
        x = self.fc1(x)
        return x


net = Net(input_size=13, output_size=1)

# loss
loss = torch.nn.MSELoss()

# optimizer
optimizer = torch.optim.SGD(net.parameters(), lr=0.01)
# optimizer = torch.optim.Adam(net.parameters(), lr=0.0001)

# training
for epoch in range(1000):
    # forward pass
    # y_pred = net(x_train_tensor)
    y_pred = net.forward(x_train_tensor)

    # compute loss
    l = loss(y_pred, y_train_tensor)

    # print(y_train_tensor.shape)
    # print(y_pred.shape)

    # backward pass
    optimizer.zero_grad()
    l.backward()
    optimizer.step()

    print(f"Epoch {epoch + 1}, Loss: {l.item()}")

    # 反标准化输出结果
    y_pred_actual = scaler_y.inverse_transform(y_pred.detach().numpy())
    y_train_actual = scaler_y.inverse_transform(y_train_tensor.detach().numpy())
    print(y_pred_actual[0:10])
    print(y_train_actual[0:10])

Epoch 1, Loss: 1.2464890480041504
[[21.206736]
 [20.574553]
 [19.067953]
 [18.832272]
 [15.357905]
 [20.46003 ]
 [20.539785]
 [17.93108 ]
 [16.013792]
 [18.64081 ]]
[[24. ]
 [21.6]
 [34.7]
 [33.4]
 [36.2]
 [28.7]
 [22.9]
 [27.1]
 [16.5]
 [18.9]]
Epoch 2, Loss: 1.0840070247650146
[[22.079338]
 [21.117325]
 [19.936348]
 [19.83087 ]
 [16.16371 ]
 [21.245657]
 [21.024658]
 [18.22839 ]
 [15.962427]
 [18.993488]]
[[24. ]
 [21.6]
 [34.7]
 [33.4]
 [36.2]
 [28.7]
 [22.9]
 [27.1]
 [16.5]
 [18.9]]
Epoch 3, Loss: 0.9561339616775513
[[22.855223]
 [21.594822]
 [20.70969 ]
 [20.712038]
 [16.873838]
 [21.933043]
 [21.448643]
 [18.487972]
 [15.905418]
 [19.298637]]
[[24. ]
 [21.6]
 [34.7]
 [33.4]
 [36.2]
 [28.7]
 [22.9]
 [27.1]
 [16.5]
 [18.9]]
Epoch 4, Loss: 0.8550900816917419
[[23.545895]
 [22.014957]
 [21.3993  ]
 [21.489964]
 [17.499891]
 [22.534182]
 [21.819145]
 [18.714428]
 [15.843711]
 [19.5621  ]]
[[24. ]
 [21.6]
 [34.7]
 [33.4]
 [36.2]
 [28.7]
 [22.9]
 [27.1]
 [16.5]
 [18.9]]
Epoch 5, Loss: 0

In [73]:
# data
data = pd.read_csv("data/HousingData.csv", sep=",")
# print(data.head())
# print(data.shape)
data = data.fillna(data.mean())
x_train = data.iloc[:496, :-1].values
y_train = data.iloc[:496, -1].values.reshape(-1, 1)
# print(x_train.shape)
# print(y_train.shape)
# print(y_train)
x_test = data.iloc[496:, :-1].values
y_test = data.iloc[496:, -1].values.reshape(-1, 1)

# standartd
scaler_y = StandardScaler()
y_train = scaler_y.fit_transform(y_train)
y_test = scaler_y.transform(y_test)
scaler_x = StandardScaler()
x_train = scaler_x.fit_transform(x_train)
x_test = scaler_x.transform(x_test)


# convert numpy to tensor
x_train_tensor = torch.tensor(x_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
# print(x_train_tensor.shape)
# print(y_train_tensor.shape)
x_test_tensor = torch.tensor(x_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32)


# Net
class Net(torch.nn.Module):
    def __init__(self, input_size, output_size):
        super(Net, self).__init__()
        self.fc1 = torch.nn.Linear(input_size, 10)
        self.ru = torch.nn.ReLU()
        self.fc2 = torch.nn.Linear(10, output_size)

    def forward(self, x):
        x = self.fc1(x)
        x = self.ru(x)
        x = self.fc2(x)
        return x


net = Net(input_size=13, output_size=1)

# loss
loss = torch.nn.MSELoss()

# optimizer
optimizer = torch.optim.SGD(net.parameters(), lr=0.01)
# optimizer = torch.optim.Adam(net.parameters(), lr=0.0001)

# training
for epoch in range(1000):
    # forward pass
    # y_pred = net(x_train_tensor)
    # y_pred = net.forward(x_train_tensor)
    y_pred = net(x_train_tensor)

    # compute loss
    l = loss(y_pred, y_train_tensor)

    # print(y_train_tensor.shape)
    # print(y_pred.shape)

    # backward pass
    optimizer.zero_grad()
    l.backward()
    optimizer.step()

    print(f"Epoch {epoch + 1}, Loss: {l.item()}")

    # 反标准化输出结果
    y_pred_actual = scaler_y.inverse_transform(y_pred.detach().numpy())
    y_train_actual = scaler_y.inverse_transform(y_train_tensor.detach().numpy())
    print(y_pred_actual[0:10])
    print(y_train_actual[0:10])

Epoch 1, Loss: 1.0452862977981567
[[24.190092]
 [23.758091]
 [24.475355]
 [24.96628 ]
 [22.984795]
 [24.478197]
 [22.868471]
 [22.484453]
 [22.29416 ]
 [22.472057]]
[[24. ]
 [21.6]
 [34.7]
 [33.4]
 [36.2]
 [28.7]
 [22.9]
 [27.1]
 [16.5]
 [18.9]]
Epoch 2, Loss: 1.0325990915298462
[[24.274017]
 [23.768032]
 [24.506676]
 [25.002642]
 [22.992447]
 [24.49986 ]
 [22.873451]
 [22.452   ]
 [22.208055]
 [22.441456]]
[[24. ]
 [21.6]
 [34.7]
 [33.4]
 [36.2]
 [28.7]
 [22.9]
 [27.1]
 [16.5]
 [18.9]]
Epoch 3, Loss: 1.0201750993728638
[[24.358065]
 [23.778208]
 [24.538874]
 [25.040007]
 [23.000631]
 [24.52237 ]
 [22.877905]
 [22.419973]
 [22.122377]
 [22.410877]]
[[24. ]
 [21.6]
 [34.7]
 [33.4]
 [36.2]
 [28.7]
 [22.9]
 [27.1]
 [16.5]
 [18.9]]
Epoch 4, Loss: 1.0080598592758179
[[24.441359]
 [23.7889  ]
 [24.565617]
 [25.07887 ]
 [23.009794]
 [24.546137]
 [22.882137]
 [22.388239]
 [22.037432]
 [22.380573]]
[[24. ]
 [21.6]
 [34.7]
 [33.4]
 [36.2]
 [28.7]
 [22.9]
 [27.1]
 [16.5]
 [18.9]]
Epoch 5, Loss: 0